# Site
title: Shellscape Software
description: Perceptions, Projects, and Software from the grey matter of Andrew Powell
url: http://shellscape.org
logo: shellscape-2016.svg
locale: en_US
excerpt_separator: <!-- more -->

assets:
  compress:
    css: false
    js: false

# Left Block Images
background:
  home: assets/images/backgrounds/home.jpg            # this image will be shown on homepage's left block
  post: assets/images/backgrounds/post.jpg            # this image will be shown when post's front matter doesn't specify any image
  post-list: assets/images/backgrounds/post-list.jpg  # this image will be shown on post list page

# Jekyll
permalink: /:categories/:year/:month/:day/:title
future: true
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
  input:            GFM
sass:
  # style:            compressed

# Google Analytics
google-analytics:   UA-78612-3

# Social Links
twitter:            shellscape
github:             shellscape
stackoverflow:      416845/shellscape
linkedin:           powellonaboat

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

# Exclude list
include: [_pages]
exclude: [README.md, Gemfile, Gemfile.lock, _site, src, vendor, CNAME, LICENSE, Rakefile, .sass-cache, .DS_Store]
